# Reference: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
spec:
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: ${IMAGE}
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
          - name: DEPLOYMENTS_DOMAIN
            value: "${DEPLOYMENTS_DOMAIN}"
          - name: ENVIRONMENT
            value: "${ENVIRONMENT}"
          - name: POSTGRES_SERVER
            value: "${POSTGRES_SERVER}"
          - name: POSTGRES_PORT
            value: "${POSTGRES_PORT}"
          - name: POSTGRES_DB
            value: "${POSTGRES_DB}"
          - name: POSTGRES_USER
            value: "${POSTGRES_USER}"
          - name: POSTGRES_SSL_ENABLED
            value: "${POSTGRES_SSL_ENABLED}"
          - name: ECR_REGISTRY_URL
            value: "${ECR_REGISTRY_URL}"
          - name: AWS_REGION
            value: "${AWS_REGION}"
          - name: POSTGRES_PASSWORD
            value: "${POSTGRES_PASSWORD}"
          - name: BUILDER_API_KEY
            value: "${BUILDER_API_KEY}"
          - name: DEPOT_PROJECT_ID
            value: "${DEPOT_PROJECT_ID}"
          - name: DEPOT_TOKEN
            value: "${DEPOT_TOKEN}"
        volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-graph-storage
      volumes:
      - name: docker-graph-storage
        emptyDir: {}

---
# Reference: https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: docker
spec:
  selector:
    app: docker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
# Reference: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: docker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docker
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
