{{- $productionLetsEncryptIssuerServer := "https://acme-v02.api.letsencrypt.org/directory" }}
{{- $stagingLetsEncryptIssuerServer := "https://acme-staging-v02.api.letsencrypt.org/directory" }}
{{- $issuerServers := dict "letsencrypt-production" $productionLetsEncryptIssuerServer "letsencrypt-staging" $stagingLetsEncryptIssuerServer }}
{{- $issuerMapping := dict "issuer" "Issuer" "clusterIssuer" "ClusterIssuer" }}
{{- range $issuer, $kind := $issuerMapping }}
{{- range $k, $i := default (dict) (index $.Values.issuers $issuer) }}
{{- $provider := default "letsencrypt" $i.provider -}}
{{- $server := default "production" $i.server -}}
---
apiVersion: cert-manager.io/v1
kind: {{ $kind }}
metadata:
  name: {{ $k | quote }}
  labels:
    {{- include "labels" (index $.Subcharts "cert-manager") | nindent 4 }}
spec:
  acme:
    # The ACME server URL
    server: {{ index $issuerServers (printf "%s-%s" $provider $server) | quote }}
    # Email address used for ACME registration
    email: certs@fastapilabs.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ $k | quote }}
    # Enable the DNS-01 challenge provider with Cloudflare API token
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: {{ include "cert-manager.cloudflare.secret-name" $ }}
            key: {{ include "cert-manager.cloudflare.secret-key" $ }}
{{- end }}
{{- end }}
