# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        exclude: ^infra/.*/templates/.*
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: ^frontend/src/client/.*
      - id: trailing-whitespace
        exclude: ^frontend/src/client/.*
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: bash -c 'cd frontend && npx @biomejs/biome check --write --files-ignore-unknown=true --no-errors-on-unmatched'
        language: system
        types: [text]
        files: ^frontend/
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.81.5
    hooks:
      - id: renovate-config-validator
        args: [--strict]

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
