services:
  db:
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - app-redis-data:/data

  nats:
    image: nats:2
    ports:
      - 4222:4222
    command: -js

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  prestart:
    build:
      context: ./backend
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: bash scripts/prestart-local.sh
    env_file:
      - .env
      - path: .env.override
        required: false
    environment:
      - POSTGRES_SERVER=db
      - REDIS_SERVER=redis
      - NATS_HOST_NAME=nats
      - SMTP_HOST=mailcatcher
    extra_hosts:
      - host.docker.internal:host-gateway

  backend:
    build:
      context: ./backend
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
      prestart:
        condition: service_completed_successfully
      redis:
        condition: service_started
      nats:
        condition: service_started
      mailcatcher:
        condition: service_started
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/api/v1/utils/health-check/",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    env_file:
      - .env
      - path: .env.override
        required: false
    environment:
      - POSTGRES_SERVER=db
      - REDIS_SERVER=redis
      - NATS_HOST_NAME=nats
      - SMTP_HOST=mailcatcher
      - LOCALSTACK_HOST_NAME=localstack
      - BUILDER_API_URL=http://builder:8001
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./backend/htmlcov:/app/htmlcov
    extra_hosts:
      - host.docker.internal:host-gateway

  builder:
    build:
      context: ./backend
      dockerfile: Dockerfile.builder
    ports:
      - "8001:8001"
    privileged: true
    env_file:
      - .env
      - path: .env.override
        required: false
    environment:
      - CI=true
      - POSTGRES_SERVER=db
      - REDIS_SERVER=redis
      - LOCALSTACK_HOST_NAME=localstack
      - BUILDER_API_URL=http://builder:8001
      - KUBERNETES_HOST=https://knative-control-plane:6443
    group_add:
      # To allow internal user to access Docker for development
      - root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Kubernetes local kubeconfig
      - ~/.kube/config:/home/user/.kube/config
    networks:
      - default
      - kind
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8001/health-check/",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    extra_hosts:
      - host.docker.internal:host-gateway

  messenger:
    build:
      context: ./backend
    depends_on:
      localstack:
        condition: service_healthy
        restart: true
      aws-cli:
        condition: service_completed_successfully
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - python
      - -m
      - app.messenger
    env_file:
      - .env
      - path: .env.override
        required: false
    environment:
      - POSTGRES_SERVER=db
      - REDIS_SERVER=redis
      - SMTP_HOST=mailcatcher
      - LOCALSTACK_HOST_NAME=localstack
      - BUILDER_API_URL=http://builder:8001
      # To run the builder in the local debugger
      # - BUILDER_API_URL=http://host.docker.internal:8001
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    extra_hosts:
      - host.docker.internal:host-gateway

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${API_HOST?Variable not set}
        - NODE_ENV=production
    ports:
      - "5173:80"

  playwright:
    build:
      context: ./frontend
      dockerfile: Dockerfile.playwright
      args:
        - VITE_API_URL=http://backend:8000
        - NODE_ENV=production
    ipc: host
    depends_on:
      - backend
      - mailcatcher
    environment:
      - VITE_API_URL=http://backend:8000
      - MAILCATCHER_HOST=http://mailcatcher:1080
      # For the reports when run locally
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - CI=${CI}
    volumes:
      - ./frontend/blob-report:/app/blob-report
      - ./frontend/test-results:/app/test-results
    ports:
      - 9323:9323
    extra_hosts:
      - host.docker.internal:host-gateway

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      # Default LocalStack suggested config
      # - "${LOCALSTACK_VOLUME_DIR:-./localstack-volume}:/var/lib/localstack"
      # Custom LocalStack config to avoid extra files in repo
      - localstack-volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:4566/_localstack/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  # To setup localstack
  aws-cli:
    image: amazon/aws-cli
    depends_on:
      localstack:
        condition: service_healthy
        restart: true
    env_file:
      - .env
      - path: .env.override
        required: false
    entrypoint: []
    command: >
      bash -c "
      aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket "${DEPLOYMENTS_BUCKET_NAME}" --region us-east-1
      && aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name "${BUILDER_QUEUE_NAME}" --attributes VisibilityTimeout=600
      "

volumes:
  app-db-data:
  app-redis-data:
  localstack-volume:

networks:
  default:
  kind:
    external: true
