apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fastapicloud.clusterrole.knative-service-manager.name" . }}
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - create
  - get
  - patch
  - update
  - delete
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fastapicloud.clusterrole.namespace-manager.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - create
  - patch
  - update
  - delete
