---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alb-oauth-secret-reader
  namespace: monitoring
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alb-oauth-secret-reader-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alb-oauth-secret-reader
subjects:
- kind: ServiceAccount
  name: aws-load-balancer-controller
  namespace: kube-system
