role: Aggregator

# extraVolumes -- Additional Volumes to use with Vector Pods.
extraVolumes:
  - name: nats-logging-write-secret
    secret:
      secretName: nats-logging-write-secret

# extraVolumeMounts -- Additional Volume to mount into Vector Containers.
extraVolumeMounts:
  - name: nats-logging-write-secret
    mountPath: /var/run/secrets/nats-logging-write-secret
    readOnly: true

# Specify custom contents for the Vector config
# ref: https://vector.dev/docs/reference/configuration/
# Note a complete and valid configuration is required. If used, the deprecated
# configuration keys will be ignored. More information can be found at:
# https://vector.dev/highlights/2021-07-13-helm-customconfig
customConfig:
  data_dir: "/vector-data-dir"
  api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false

  sources:
    internal_metrics:
      type: internal_metrics
    vector:
      address: 0.0.0.0:6000
      type: vector
      version: "2"

  transforms:
    filter_knative:
      type: filter
      inputs:
        - vector
      condition: exists(.kubernetes.pod_labels.fastapicloud_app) && .kubernetes.container_name == "user-container"

  sinks:
    prom_exporter:
      type: prometheus_exporter
      inputs: [internal_metrics]
      address: 0.0.0.0:9090
    stdout:
      type: console
      inputs:
        - filter_knative
      encoding:
        codec: json
    nats_logging:
      type: nats
      inputs:
        - filter_knative
      encoding:
        codec: json
      # Vector template inside Helm template
      # Ref: https://github.com/vectordotdev/helm-charts/tree/develop/charts/vector#using-template-syntax-in-customconfig
      subject: |-
        {{ `logs.apps.{{ .kubernetes.pod_labels.fastapicloud_team }}.{{ .kubernetes.pod_labels.fastapicloud_app }}.{{ .kubernetes.pod_labels.fastapicloud_deployment }}` }}
      url: tls://connect.ngs.global
      auth:
        strategy: credentials_file
        credentials_file:
          path: /var/run/secrets/nats-logging-write-secret/nats.creds
