apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  # This is Let's Encrypt staging issuer, it has nothing to do with our staging environment
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: certs@fastapilabs.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production
    # Enable the DNS-01 challenge provider with Cloudflare API token
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
