# Reference: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger
  namespace: fastapicloud
spec:
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      serviceAccountName: fastapicloud
      containers:
      - name: messenger
        image: ${IMAGE}
        command:
          - python
          - -m
          - app.messenger
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
          - name: ENVIRONMENT
            value: "${ENVIRONMENT}"
          - name: AWS_REGION
            value: "${AWS_REGION}"
          - name: DEPLOYMENTS_BUCKET_NAME
            value: "${DEPLOYMENTS_BUCKET_NAME}"
          - name: BUILDER_QUEUE_NAME
            value: "${BUILDER_QUEUE_NAME}"
          - name: BUILDER_API_KEY
            value: "${BUILDER_API_KEY}"
          - name: BUILDER_API_URL
            value: "${BUILDER_API_URL}"
          - name: MESSENGER_SENTRY_DSN
            value: "${MESSENGER_SENTRY_DSN}"
          - name: LOGFIRE_TOKEN
            value: "${LOGFIRE_TOKEN}"
          - name: REDIS_SERVER
            value: "${REDIS_SERVER}"
          - name: NATS_HOST_NAME
            value: "${NATS_HOST_NAME}"
          - name: NATS_CREDS
            value: "${NATS_CREDS_JSON_STR}"

---
# Reference: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: messenger-hpa
  namespace: fastapicloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: messenger
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
