apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: activator
  namespace: knative-serving
spec:
  minReplicas: 3
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webhook
  namespace: knative-serving
spec:
  minReplicas: 2
