apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - image: 992382821657.dkr.ecr.us-east-1.amazonaws.com/fastapi-labs-backend@sha256:782c4ebae7efcd0dd0d69b1c98c13a22c1372d489c7e38b437f179b7df7a956a
        name: api
        ports:
        - containerPort: 8888
        command: ["/start-reload.sh"]
        envFrom:
        - configMapRef:
            name: fastapi-backend-config
        - secretRef:
            name: fastapi-backend-secrets
