apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: git@github.com:fastapilabs/cloud.git
    targetRevision: HEAD
    path: infra/k8s/knative/kustomize/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
