[project]
name = "fastapicloud-cloudflare"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-cloudflare>=6.0.0,<7.0.0",
    "pydantic>=2.0.0,<3.0.0",
]
