k8s-monitoring:
  # Configure destinations to point to local services
  destinations:
    - name: metrics-mimir
      type: prometheus
      url: http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push

    - name: logs-loki
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
      tenantId: "1"

    - name: traces-tempo
      type: otlp
      url: http://tempo.monitoring.svc.cluster.local:4317/v1/traces
      protocol: grpc
      metrics: { enabled: false }
      logs:    { enabled: false }
      traces:  { enabled: true }

  # Collectors configuration
  alloy-metrics:
    enabled: true
    alloy:
      enableReporting: false
      resources:
        requests:
          cpu: 10m
          memory: 512Mi
        limits:
          memory: 512Mi

  alloy-logs:
    enabled: true
    alloy:
      enableReporting: false
      resources:
        requests:
          cpu: 10m
          memory: 256Mi
        limits:
          memory: 256Mi

  alloy-receiver:
    enabled: true
    alloy:
      enableReporting: false
      resources:
        requests:
          cpu: 10m
          memory: 256Mi
        limits:
          memory: 256Mi
      extraPorts:
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP
        - name: otlp-http
          port: 4318
          targetPort: 4318
          protocol: TCP
        - name: zipkin
          port: 9411
          targetPort: 9411
          protocol: TCP
        # - name: jaeger-compact
        #   port: 6831
        #   targetPort: 6831
        #   protocol: UDP
        # - name: jaeger-grpc
        #   port: 14250
        #   targetPort: 14250
        #   protocol: TCP
        # - name: jaeger-http
        #   port: 14268
        #   targetPort: 14268
        #   protocol: TCP

  alloy-singleton:
    enabled: true
    alloy:
      enableReporting: false
      resources:
        requests:
          cpu: 10m
          memory: 512Mi
        limits:
          memory: 512Mi
    extraConfig: |-
      mimir.rules.kubernetes "default" {
        address = "http://mimir-ruler.monitoring.svc:8080"
        tenant_id = "anonymous"
      }

  clusterMetrics:
    enabled: true

    apiServer:
      enabled: true
      scrapeInterval: 30s

    cadvisor:
      enabled: true
      scrapeInterval: 30s

    controlPlane:
      enabled: true

    kubelet:
      enabled: true
      scrapeInterval: 30s

    opencost:
      enabled: false

    # lol
    windows-exporter:
      enabled: false
      deploy: false

    # energy metrics
    kepler:
      enabled: false

  # Feature: Cluster Events
  clusterEvents:
    enabled: true

  # Feature: Pod Logs
  podLogs:
    enabled: true

  # Feature: Node Logs
  nodeLogs:
    enabled: true

  # Feature: Application Observability
  applicationObservability:
    enabled: true

    connectors:
      grafanaCloudMetrics:
        enabled: false

    receivers:
      otlp:
        grpc:
          enabled: true
          port: 4317
        http:
          enabled: true
          port: 4318
      zipkin:
        enabled: true
        port: 9411

  # Feature: Annotation Autodiscovery
  annotationAutodiscovery:
    enabled: true

  # Feature: Prometheus Operator Objects
  prometheusOperatorObjects:
    enabled: true

  # Feature: Profiling
  profiling:
    enabled: false

  # Feature: Auto-instrumentation
  autoInstrumentation:
    enabled: false
