tempo:
  fullnameOverride: tempo

  serviceMonitor:
    enabled: true

  tempo:
    reportingEnabled: false

    metricsGenerator:
      enabled: true
      remoteWriteUrl: http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push
