{{- range $k, $cfg := default (dict) .Values.config.stores -}}
apiVersion: external-secrets.io/v1beta1
kind: {{ default $.Values.config.kind $cfg.kind }}
metadata:
  name: external-{{ $k }}
  labels:
    {{- include "external-secrets.labels" $ | nindent 4 }}
  {{- with $cfg.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    {{- toYaml $cfg.provider | nindent 4 }}
{{- end -}}
