tempo:
  serviceAccount:
    create: true
    name: tempo
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::961341535962:role/tempo-irsa-development"

  tempo:
    storage:
      trace:
        backend: s3
        s3:
          bucket: "fastapicloud-tempo-development"
          region: "us-east-1"
          endpoint: "s3.us-east-1.amazonaws.com"
