name: Deploy UI - Staging
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  deployments: write
  issues: write
  pull-requests: write
  statuses: write

jobs:
  build-and-deploy-ui:
    if: ( github.event_name != 'pull_request' || github.secret_source == 'Actions' )
    strategy:
      matrix:
        environment:
          - staging
          - development
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
      - run: rm -rf ./frontend/dist
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.15"
      - run: npm ci
        working-directory: frontend
      - run: npm run build
        env:
          VITE_API_URL: ${{ vars.API_HOST }}
        working-directory: frontend
      - name: Deploy to Cloudflare Pages
        # hashFiles returns an empty string if there are no files
        if: hashFiles('./frontend/dist/*')
        id: deploy
        env:
          PROJECT_NAME: ${{ matrix.environment == 'staging' && 'dashboard-fastapicloud-work' || matrix.environment == 'development' && 'dashboard-fastapicloud-site' }}
          BRANCH: ${{ github.event_name == 'pull_request' && 'preview' || github.event_name == 'push' && 'main' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./frontend/dist --project-name=${{ env.PROJECT_NAME }} --branch=${{ env.BRANCH }}
      - name: Install GitHub Actions dependencies
        run: |
          uv venv
          uv pip install -r requirements-github-actions.txt
      - name: Comment Deploy
        run: uv run python ./scripts/deploy_ui_status.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_URL: ${{ steps.deploy.outputs.deployment-url }}
          COMMIT_SHA: ${{ github.sha }}
          PR_NUMBER: ${{ github.event.number }}
          ENVIRONMENT: ${{ matrix.environment }}

  # https://github.com/marketplace/actions/alls-green#why
  deploy-ui-alls-green:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - build-and-deploy-ui
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
