name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'infra/k8s/knative/backend/**'
      - '.github/workflows/deploy-backend-staging.yml'

env:
  ECR_REPOSITORY: fastapicloud-backend
  IMAGE_TAG: staging-${{ github.sha }}

jobs:
  deploy-backend:
    name: Deploy Backend
    strategy:
      matrix:
        environment:
          - staging
          - development
    runs-on: ${{ matrix.environment }}
    environment: ${{ matrix.environment }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.15"
    - name: Install kubectl
      uses: azure/setup-kubectl@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    - name: Login to Amazon ECR
      with:
        mask-password: True
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build and push Docker images to Amazon ECR
      uses: docker/build-push-action@v6
      id: docker-build
      with:
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        context: ./backend/
    - name: Run migrations
      run: uv run bash scripts/prestart.sh
      working-directory: backend
      env:
        # Env vars for the app
        DOMAIN: "${{ vars.DOMAIN }}"
        FRONTEND_HOST: "${{ vars.FRONTEND_HOST }}"
        API_HOST: "${{ vars.API_HOST }}"
        ENVIRONMENT: "staging"
        PROJECT_NAME: "${{ vars.PROJECT_NAME }}"
        STACK_NAME: "${{ vars.STACK_NAME }}"
        BACKEND_CORS_ORIGINS: "${{ vars.BACKEND_CORS_ORIGINS }}"
        FIRST_SUPERUSER: "${{ vars.FIRST_SUPERUSER }}"
        FIRST_SUPERUSER_FULL_NAME: "${{ vars.FIRST_SUPERUSER_FULL_NAME }}"
        USERS_OPEN_REGISTRATION: "${{ vars.USERS_OPEN_REGISTRATION }}"
        SMTP_HOST: "${{ vars.SMTP_HOST }}"
        SMTP_USER: "${{ vars.SMTP_USER }}"
        EMAILS_FROM_EMAIL: "${{ vars.EMAILS_FROM_EMAIL }}"
        SMTP_TLS: "${{ vars.SMTP_TLS }}"
        SMTP_SSL: "${{ vars.SMTP_SSL }}"
        SMTP_PORT: "${{ vars.SMTP_PORT }}"
        POSTGRES_SERVER: "${{ vars.POSTGRES_SERVER }}"
        POSTGRES_PORT: "${{ vars.POSTGRES_PORT }}"
        POSTGRES_DB: "${{ vars.POSTGRES_DB }}"
        POSTGRES_USER: "${{ vars.POSTGRES_USER }}"
        POSTGRES_SSL_ENABLED: "${{ vars.POSTGRES_SSL_ENABLED }}"
        REDIS_SERVER: "${{ vars.REDIS_SERVER }}"
        SENTRY_DSN: "${{ vars.SENTRY_DSN }}"
        DOCKER_IMAGE_BACKEND: "${{ vars.DOCKER_IMAGE_BACKEND }}"
        DOCKER_IMAGE_FRONTEND: "${{ vars.DOCKER_IMAGE_FRONTEND }}"
        AWS_DEPLOYMENT_BUCKET: "${{ vars.AWS_DEPLOYMENT_BUCKET }}"
        ECR_REGISTRY_URL: "${{ vars.ECR_REGISTRY_URL }}"

        # Secrets for the app
        SECRET_KEY: "${{ secrets.SECRET_KEY }}"
        FIRST_SUPERUSER_PASSWORD: "${{ secrets.FIRST_SUPERUSER_PASSWORD }}"
        SMTP_PASSWORD: "${{ secrets.SMTP_PASSWORD }}"
        POSTGRES_PASSWORD: "${{ secrets.POSTGRES_PASSWORD }}"
    - name: Update Knative Service image
      run: uv run typer --func deploy_cloud app.docker_builder run api $IMAGE_URL $IMAGE_DIGEST --min-scale 1
      working-directory: backend
      env:
        IMAGE_URL: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
        IMAGE_DIGEST: ${{ steps.docker-build.outputs.digest }}

        # Env vars for the app
        DOMAIN: "${{ vars.DOMAIN }}"
        FRONTEND_HOST: "${{ vars.FRONTEND_HOST }}"
        API_HOST: "${{ vars.API_HOST }}"
        ENVIRONMENT: "staging"
        PROJECT_NAME: "${{ vars.PROJECT_NAME }}"
        STACK_NAME: "${{ vars.STACK_NAME }}"
        BACKEND_CORS_ORIGINS: "${{ vars.BACKEND_CORS_ORIGINS }}"
        FIRST_SUPERUSER: "${{ vars.FIRST_SUPERUSER }}"
        FIRST_SUPERUSER_FULL_NAME: "${{ vars.FIRST_SUPERUSER_FULL_NAME }}"
        USERS_OPEN_REGISTRATION: "${{ vars.USERS_OPEN_REGISTRATION }}"
        SMTP_HOST: "${{ vars.SMTP_HOST }}"
        SMTP_USER: "${{ vars.SMTP_USER }}"
        EMAILS_FROM_EMAIL: "${{ vars.EMAILS_FROM_EMAIL }}"
        SMTP_TLS: "${{ vars.SMTP_TLS }}"
        SMTP_SSL: "${{ vars.SMTP_SSL }}"
        SMTP_PORT: "${{ vars.SMTP_PORT }}"
        POSTGRES_SERVER: "${{ vars.POSTGRES_SERVER }}"
        POSTGRES_PORT: "${{ vars.POSTGRES_PORT }}"
        POSTGRES_DB: "${{ vars.POSTGRES_DB }}"
        POSTGRES_USER: "${{ vars.POSTGRES_USER }}"
        POSTGRES_SSL_ENABLED: "${{ vars.POSTGRES_SSL_ENABLED }}"
        REDIS_SERVER: "${{ vars.REDIS_SERVER }}"
        SENTRY_DSN: "${{ vars.SENTRY_DSN }}"
        DOCKER_IMAGE_BACKEND: "${{ vars.DOCKER_IMAGE_BACKEND }}"
        DOCKER_IMAGE_FRONTEND: "${{ vars.DOCKER_IMAGE_FRONTEND }}"
        AWS_DEPLOYMENT_BUCKET: "${{ vars.AWS_DEPLOYMENT_BUCKET }}"
        ECR_REGISTRY_URL: "${{ vars.ECR_REGISTRY_URL }}"

        # Secrets for the app
        SECRET_KEY: "${{ secrets.SECRET_KEY }}"
        FIRST_SUPERUSER_PASSWORD: "${{ secrets.FIRST_SUPERUSER_PASSWORD }}"
        SMTP_PASSWORD: "${{ secrets.SMTP_PASSWORD }}"
        POSTGRES_PASSWORD: "${{ secrets.POSTGRES_PASSWORD }}"
