name: Format Frontend

on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  changes:
    runs-on: depot-ubuntu-22.04
    # Required permissions
    permissions:
      pull-requests: read
      contents: read
    # Set job outputs to values from filter step
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
    - uses: actions/checkout@v4
    # For pull requests it's not necessary to checkout the code but for the main branch it is
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          changed:
            - frontend/**
            - .github/workflows/format-frontend.yml

  format-frontend:
    needs:
      - changes
    if: ${{ needs.changes.outputs.changed == 'true' }}
    permissions:
      contents: write
    runs-on: depot-ubuntu-22.04
    steps:
    # For PRs from forks and bots
    - uses: actions/checkout@v4
    # For PRs from the same repo
    - uses: actions/checkout@v4
      if: ( github.event_name != 'pull_request' || github.secret_source == 'Actions' )
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
      working-directory: frontend
    - name: Format frontend
      run: |
        npm run biome-check
      working-directory: frontend
    - name: Add changes to git
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git add frontend
    # Same repo PRs
    - name: Push changes
      if: ( github.event_name != 'pull_request' || github.secret_source == 'Actions' )
      run: |
        git diff --staged --quiet || git commit -m "🎨 Format frontend code"
        git push
    # Fork and bot PRs
    - name: Check changes
      if: ( github.event_name == 'pull_request' && github.secret_source != 'Actions' )
      run: |
        git diff --staged --quiet || (echo "Changes detected in, run npm run biome-check --write and commit the changes" && exit 1)

  # https://github.com/marketplace/actions/alls-green#why
  alls-green-format-frontend:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - format-frontend
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: format-frontend
