name: Lint Backend

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  changes:
    runs-on: depot-ubuntu-22.04
    # Required permissions
    permissions:
      pull-requests: read
      contents: read
    # Set job outputs to values from filter step
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
    - uses: actions/checkout@v4
    # For pull requests it's not necessary to checkout the code but for the main branch it is
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          changed:
            - backend/**
            - .env
            - scripts/lint.sh
            - .github/workflows/lint-backend.yml

  lint-backend:
    needs:
      - changes
    if: ${{ needs.changes.outputs.changed == 'true' }}
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.4.15"
      - run: uv run bash scripts/lint.sh
        working-directory: backend

  # https://github.com/marketplace/actions/alls-green#why
  alls-green-lint-backend:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - lint-backend
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: lint-backend
