name: Pulumi Preview
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  changes:
    runs-on: depot-ubuntu-22.04
    # Required permissions
    permissions:
      pull-requests: read
      contents: read
    # Set job outputs to values from filter step
    outputs:
      k8s: ${{ steps.filter.outputs.k8s }}
      cloudflare: ${{ steps.filter.outputs.cloudflare }}
      workflow: ${{ steps.filter.outputs.workflow }}
    steps:
    - uses: actions/checkout@v5
    # For pull requests it's not necessary to checkout the code but for the main branch it is
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        predicate-quantifier: 'every'
        filters: |
          k8s:
            - 'infra/pulumi/k8s-cluster/**'
          cloudflare:
            - 'infra/pulumi/cloudflare/**'
          workflow:
            - '.github/workflows/pulumi-preview.yml'

  pulumi-preview:
    needs:
      - changes
    if: ${{ (needs.changes.outputs.k8s == 'true' || needs.changes.outputs.workflow == 'true') && (github.event_name != 'pull_request' || github.secret_source == 'Actions') }}
    environment: staging
    name: Pulumi Preview
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8"
          enable-cache: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install dependencies
        run: uv sync
        working-directory: infra/pulumi/k8s-cluster
      - uses: pulumi/actions@v6
        with:
          command: preview
          # stack-name: org-name/stack-name # When using an individual account, only use stack-name.
          stack-name: fastapilabs/staging
          work-dir: infra/pulumi/k8s-cluster
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN_SSL: ${{ secrets.CLOUDFLARE_API_TOKEN_SSL }}
          NATS_LOGGING_WRITE_CREDS: ${{ secrets.NATS_CREDS }}

  cloudflare-preview:
    needs:
      - changes
    if: ${{ (needs.changes.outputs.cloudflare == 'true' || needs.changes.outputs.workflow == 'true') && (github.event_name != 'pull_request' || github.secret_source == 'Actions') }}
    environment: staging
    name: Cloudflare Preview
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8"
          enable-cache: true
      - name: Install dependencies
        run: uv sync
        working-directory: infra/pulumi/cloudflare
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: fastapilabs/cloudflare-stack/production
          work-dir: infra/pulumi/cloudflare
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  # https://github.com/marketplace/actions/alls-green#why
  alls-green-pulumi-preview:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - pulumi-preview
      - cloudflare-preview
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: pulumi-preview, cloudflare-preview
