name: Pulumi
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  preview:
    name: Pulumi Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Configure AWS Credentials
        if: github.actor != 'dependabot[bot]'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-region: ${{ secrets.AWS_REGION_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      - run: pip install -r requirements.txt
        if: github.actor != 'dependabot[bot]'
        working-directory: infra
      - uses: pulumi/actions@v5
        if: github.actor != 'dependabot[bot]'
        with:
          command: preview
          # stack-name: org-name/stack-name # When using an individual account, only use stack-name.
          stack-name: fastapilabs/staging
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
