name: Pulumi Preview
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  changes:
    runs-on: depot-ubuntu-22.04
    # Required permissions
    permissions:
      pull-requests: read
      contents: read
    # Set job outputs to values from filter step
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
    - uses: actions/checkout@v4
    # For pull requests it's not necessary to checkout the code but for the main branch it is
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          changed:
            - infra/**
            - .github/workflows/pulumi-preview.yml

  pulumi-preview:
    needs:
      - changes
    if: ${{ needs.changes.outputs.changed == 'true' && (github.event_name != 'pull_request' || github.secret_source == 'Actions') }}
    environment: staging
    name: Pulumi Preview
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: pip install -r requirements.txt
        working-directory: infra
      - uses: pulumi/actions@v6
        with:
          command: preview
          # stack-name: org-name/stack-name # When using an individual account, only use stack-name.
          stack-name: fastapilabs/staging
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  # https://github.com/marketplace/actions/alls-green#why
  alls-green-pulumi-preview:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - pulumi-preview
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: pulumi-preview
