name: Pulumi
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  preview:
    if: github.actor != 'dependabot[bot]'
    name: Pulumi Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-region: ${{ secrets.AWS_REGION_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      - run: pip install -r requirements.txt
        working-directory: infra
      - uses: pulumi/actions@v3
        with:
          command: preview
          # stack-name: org-name/stack-name # When using an individual account, only use stack-name.
          stack-name: staging
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  # https://github.com/marketplace/actions/alls-green#why
  pulumi-alls-green:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - preview
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
