name: Test Packages

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: "false"

jobs:
  changes:
    runs-on: depot-ubuntu-22.04
    # Required permissions
    permissions:
      pull-requests: read
      contents: read
    # Set job outputs to values from filter step
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
      # For pull requests it's not necessary to checkout the code but for the main branch it is
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - packages/**
              - .github/workflows/test-packages.yml

  test-packages:
    needs:
      - changes
    if: ${{ needs.changes.outputs.changed == 'true' }}
    strategy:
      matrix:
        package:
          - duck
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.14"
      # Allow debugging with tmate
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}
        with:
          limit-access-to-actor: true
      - name: Run tests
        run: |
          uv run coverage run -m pytest
          uv run coverage report
          uv run coverage html --title "Coverage for ${{ github.sha }}"

        working-directory: packages/${{ matrix.package }}
      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: packages/${{ matrix.package }}/htmlcov
          include-hidden-files: true

  # https://github.com/marketplace/actions/alls-green#why
  alls-green-test-packages: # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - test-packages
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: test-packages
