name: Test Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  changes:
    runs-on: depot-ubuntu-22.04
    # Required permissions
    permissions:
      pull-requests: read
      contents: read
    # Set job outputs to values from filter step
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
    - uses: actions/checkout@v4
    # For pull requests it's not necessary to checkout the code but for the main branch it is
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          changed:
            - backend/**
            - frontend/**
            - .env
            - compose.yml
            - .github/workflows/test-docker-compose.yml

  test-docker-compose:
    needs:
      - changes
    if: ${{ needs.changes.outputs.changed == 'true' }}
    runs-on: depot-ubuntu-22.04
    # Permissions for Depot Docker build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: depot/setup-action@v1
      # - run: docker compose build
      - run: depot bake --load
        env:
          DEPOT_PROJECT_ID: ${{ vars.DEPOT_PROJECT_ID }}
      - run: docker compose down -v --remove-orphans
      - run: docker compose up -d --wait backend frontend builder adminer
      - name: Test backend is up
        run: curl http://localhost:8000/api/v1/utils/health-check
      - name: Test builder is up
        run: curl http://localhost:8088/health-check
      - name: Test frontend is up
        run: curl http://localhost:5173
      - run: docker compose down -v --remove-orphans

  # https://github.com/marketplace/actions/alls-green#why
  alls-green-test-docker-compose:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - test-docker-compose
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: test-docker-compose
