name: Update EKS Versions

on:
  schedule:
    # Every Monday at 8am UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  update-eks-versions:
    runs-on: depot-ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write

    environment: staging

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ${{ vars.AWS_REGION }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Check for EKS updates
      id: check
      run: |
        # Get all supported EKS versions and find the latest
        LATEST_EKS=$(aws eks describe-addon-versions --addon-name vpc-cni --output json | \
          jq -r '.addons[0].addonVersions[].compatibilities[].clusterVersion' | \
          sort -V | tail -n 1)

        # Get all addon versions in one call and extract with jq
        ADDONS_JSON=$(aws eks describe-addon-versions --kubernetes-version "$LATEST_EKS" --output json)

        LATEST_KUBE_PROXY=$(echo "$ADDONS_JSON" | jq -r '.addons[] | select(.addonName=="kube-proxy") | .addonVersions[0].addonVersion')
        LATEST_COREDNS=$(echo "$ADDONS_JSON" | jq -r '.addons[] | select(.addonName=="coredns") | .addonVersions[0].addonVersion')
        LATEST_VPC_CNI=$(echo "$ADDONS_JSON" | jq -r '.addons[] | select(.addonName=="vpc-cni") | .addonVersions[0].addonVersion')
        LATEST_EBS_CSI=$(echo "$ADDONS_JSON" | jq -r '.addons[] | select(.addonName=="aws-ebs-csi-driver") | .addonVersions[0].addonVersion')

        # SSM Parameter Store has the officially tested AMI for each EKS version
        LATEST_AMI_ID=$(aws ssm get-parameter --name /aws/service/eks/optimized-ami/${LATEST_EKS}/amazon-linux-2023/x86_64/standard/recommended/image_id --query "Parameter.Value" --output text)

        echo "Latest versions: EKS=$LATEST_EKS, AMI=$LATEST_AMI_ID, CoreDNS=$LATEST_COREDNS, kube-proxy=$LATEST_KUBE_PROXY, VPC-CNI=$LATEST_VPC_CNI, EBS-CSI=$LATEST_EBS_CSI"

        # Apply to all environments to ensure consistency
        for env in development staging production; do
          yq -i ".config.\"k8s-cluster:eks_cluster_version\" = \"$LATEST_EKS\"" infra/pulumi/k8s-cluster/Pulumi.$env.yaml
          yq -i ".config.\"k8s-cluster:eks_node_ami_id\" = \"$LATEST_AMI_ID\"" infra/pulumi/k8s-cluster/Pulumi.$env.yaml
          yq -i ".config.\"k8s-cluster:eks_coredns_version\" = \"$LATEST_COREDNS\"" infra/pulumi/k8s-cluster/Pulumi.$env.yaml
          yq -i ".config.\"k8s-cluster:eks_kube_proxy_version\" = \"$LATEST_KUBE_PROXY\"" infra/pulumi/k8s-cluster/Pulumi.$env.yaml
          yq -i ".config.\"k8s-cluster:eks_vpc_cni_version\" = \"$LATEST_VPC_CNI\"" infra/pulumi/k8s-cluster/Pulumi.$env.yaml
          yq -i ".config.\"k8s-cluster:eks_ebs_csi_version\" = \"$LATEST_EBS_CSI\"" infra/pulumi/k8s-cluster/Pulumi.$env.yaml
        done

        # Only create PR if versions actually changed
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.check.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        commit-message: "⬆ Update EKS version and addon versions"
        title: "⬆ Update EKS version and addon versions"
        body: |
          This PR updates the EKS cluster version and addon versions (CoreDNS, kube-proxy, VPC CNI, EBS CSI) along with the node AMI to the latest available.

          Please review the changes and test in staging before merging.
        branch: update-eks-versions
        delete-branch: true
